import {
  ABOUT,
  AVAILABILITY,
  COLLAPSE,
  CONTACT,
  ENGAGE,
  FAQ,
  HERO,
  PROOF_CELLS,
  SERVICES,
  SITE,
  TOOLKIT,
  WORK,
} from '~/content/site'

/**
 * SEO-10: the full page content as clean markdown at a stable URL, linked from
 * the footer with rel="alternate". Generated from content/site.ts so it is
 * always the same copy the page renders.
 *
 * FR-704 holds here too: no organisation is named.
 */
export default defineEventHandler((event) => {
  const lines = [
    `# ${SITE.name}`,
    '',
    `*${SITE.role}*`,
    '',
    HERO.eyebrow,
    '',
    `## ${HERO.h1}`,
    '',
    HERO.standfirst,
    '',
    '---',
    '',
    '## Track record',
    '',
    ...PROOF_CELLS.map((cell) => `- **${cell.value}** ${cell.label}`),
    '',
    `## ${COLLAPSE.h2}`,
    '',
    COLLAPSE.body,
    '',
    ...COLLAPSE.steps.map((step) => `${step.number}. ${step.label}`),
    '',
    ...COLLAPSE.cards.map((card) => `- **${card.number} ${card.label}** — ${card.footnote}`),
    '',
    COLLAPSE.caption,
    '',
    `## ${SERVICES.h2}`,
    '',
    SERVICES.body,
    '',
    ...SERVICES.tracks.flatMap((track) => [
      `### ${track.eyebrow}: ${track.heading}`,
      '',
      track.description,
      '',
      ...track.deliverables.map((d) => `- ${d}`),
      '',
    ]),
    `## ${ENGAGE.h2}`,
    '',
    ENGAGE.body,
    '',
    ...ENGAGE.models.flatMap((model) => [
      `### ${model.name}`,
      '',
      `- Shape: ${model.shape}`,
      `- Typical outcome: ${model.outcome}`,
      '',
    ]),
    `## ${WORK.h2}`,
    '',
    WORK.body,
    '',
    ...WORK.cases.flatMap((note) => [
      `### ${note.index}`,
      '',
      `- Sector: ${note.sector}`,
      `- Duration: ${note.duration}`,
      '',
      ...note.parts.map((part) => `**${part.label}.** ${part.text}`),
      '',
    ]),
    `## ${TOOLKIT.h2}`,
    '',
    ...TOOLKIT.groups.flatMap((group) => [
      `### ${group.heading}`,
      '',
      ...group.items.map((item) => `- ${item}`),
      '',
    ]),
    `## ${ABOUT.h2}`,
    '',
    ...ABOUT.paragraphs.flatMap((p) => [p, '']),
    `> ${ABOUT.pullQuote}`,
    '',
    `## ${AVAILABILITY.h2}`,
    '',
    AVAILABILITY.body,
    '',
    ...AVAILABILITY.rows.map((row) => `- **${row.label}:** ${row.value}`),
    '',
    '## Questions',
    '',
    ...FAQ.items.flatMap((item) => [`### ${item.question}`, '', item.answer, '']),
    `## ${CONTACT.h2}`,
    '',
    CONTACT.body,
    '',
    `- Email: ${SITE.email}`,
    `- LinkedIn: ${SITE.linkedin}`,
    `- X: ${SITE.x}`,
    '',
    `*Last updated ${SITE.lastUpdated}.*`,
    '',
  ]

  setResponseHeader(event, 'content-type', 'text/markdown; charset=utf-8')
  return lines.join('\n')
})
